### ISSUE TITLE
minimap_pipeline:makeReport (1) error with custom database

### ISSUE THREAD

**Issue by jadeaver** [epi2me-labs/wf-16s#25]
I created a custom database following the documentation provided in this [tutorial](https://labs.epi2me.io/how-to-meta-offline/#the-structure-and-composition-of-the-databases). I successfully created the taxdump files, minimap2 database, and ref2taxid file. The wf-16s pipeline runs as expected until the makeReport step where I encounter the error "Process `minimap_pipeline:makeReport (1)` terminated with an error exit status (1)" with "KeyError: "The following 'id_vars' are not present in the DataFrame: ['species']" (please see full log file attached). I do get the abundances table output, so perhaps I don't really need the full report. However, my question is what may be causing this error and is there a file I might need to fix in my custom database to be able to get the full report output?
[nextflow.log](https://github.com/user-attachments/files/16548030/nextflow.log)

**Comment by nggvs** [comment]
Hi @jadeaver ,

Thanks for using the workflow! It seems something weird. Would you mind to reopen the issue as a bug (you'd need to use the bug template)? So that I can have more info about the params that you're using?

Also if you could paste the first lines of the abundance table that you're getting to have an idea of how it looks like I think it would be helpful.

Thank you very much in advance!

**Comment by jadeaver** [comment]
Re-opened this issue as a bug (https://github.com/epi2me-labs/wf-16s/issues/26). Closing this question.
