### ISSUE TITLE
Grouping of samples

### ISSUE THREAD

**Issue by joe0750** [epi2me-labs/wf-16s#4]
### Ask away!

I see that this gives alpha and beta diversity and other measures for individual samples.  Is there a way to group samples and compare groups with this analysis?

**Comment by nggvs** [comment]
Hi!
First of all, thank you for using the pipeline!    
Unfortunately we don't offer yet the possibility of using metadata to group samples based on different factors (which I guess is what you would like to have). 
Nevertheless, I note your suggestion to consider it for future releases, could you give an example on what you would like to have?

Thank you in advance,
Natalia

**Comment by nggvs** [comment]
Hi @joe0750 ,
Are you still interested in this feature? Could you provide an example of what you would like to have and why?
Thank you very much!

**Comment by joe0750** [comment]
Jaccard distances, bray-curtis distance, weighted UniFrac and unweighted UniFrac as these are the measures I am acquainted with from qiime analyses.  I can compare the alpha diversity measures already provided, but understanding diversity within a group of samples allows for understanding community dynamics while comparing to another group of individuals.

**Comment by nggvs** [comment]
Hi @joe0750 ,
Thank you very much for the suggestions! I have considered to add more diversity metrics as the ones you have proposed but is not very straight-forward as they would require normalizing the data (and this can depend on the type of your experiment, so we should offer different types of normalization). Also probably you would like to group your samples in different ways (for example in the case of marine samples by ocean, by depth...) which implies categorical and continuous groupings. 
I keep this in mind because it definitely enrich the workflow but I'm afraid is not going to be implemented short term.
Thank you for using the workflow and hope you find it useful for the first part of the analysis so then you can do more advance analysis with the results!
